name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        env:
          CI: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Test Code
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: npm test
